apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  labels:
    app: my-flask-app
spec:
  type: LoadBalancer # Expose the service externally using a cloud provider's load balancer
  ports:
    - port: 80 # The port the LoadBalancer will listen on
      targetPort: 5000 # The port our container is listening on
      protocol: TCP
  selector:
    app: my-flask-app # Selects Pods with the label app: my-flask-app